var: 80
maximum1: 50
maximum2: 255
minimum: 6
gra: 50
number_page: 5
link_email:  http://gravatar.com/emails
password_reset_expired: 2
<<<<<<< HEAD
user_post_paginate: 10
url_rails: "http://www.railstutorial.org/"
url_ruby: "http://rubyonrails.org/"
rails_png: "rails.png"
post: 140
five_mb: 5
img: 400
=======
>>>>>>> 04d2d94... Add password reset
